/**
 * Códigos de error del sistema
 */
const ErrorCodes = {
  // Errores de dominio
  DOMAIN_ERROR: 'DOMAIN_ERROR',
  INVOICE_VALIDATION_ERROR: 'INVOICE_VALIDATION_ERROR',
  DOCUMENT_VALIDATION_ERROR: 'DOCUMENT_VALIDATION_ERROR',

  // Errores de procesamiento
  DOCUMENT_EXTRACTION_ERROR: 'DOCUMENT_EXTRACTION_ERROR',
  DOCUMENT_PARSING_ERROR: 'DOCUMENT_PARSING_ERROR',
  DOCUMENT_STORAGE_ERROR: 'DOCUMENT_STORAGE_ERROR',

  // Errores de sistema
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  PERMISSION_ERROR: 'PERMISSION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = { ErrorCodes };
